/*
 * eu.operando.interfaces.aapi
 * Operandos AS interfaces
 *
 * OpenAPI spec version: 0.0.1
 * Contact: kpatsak@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.operando.core.cas.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
