# I take a official apereo/cas
# we choose normal 
FROM tomcat:7

RUN wget https://raw.githubusercontent.com/osixia/docker-light-baseimage/stable/image/service-available/%3Assl-tools/assets/default-ca/default-ca.pem
# RUN keytool -alias openldapsrv -import -file default-ca.pem -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -noprompt

# Exposed ports by parent docker
# EXPOSE 8080 8443

