# I take a official mono image https://hub.docker.com/_/mono/
# we choose normal 
FROM osixia/phpldapadmin:0.6.12

ENV PHPLDAPADMIN_LDAP_HOSTS=openldap.as.integration.operando.lan.esilab.org

# EXPOSE 80

# CMD [ "phpmyadmin/phpmyadmin" ]