# I take a official mono image https://hub.docker.com/_/mono/
# we choose normal 
FROM phpmyadmin/phpmyadmin

ENV MYSQL_ROOT_PASSWORD=root
ENV PMA_HOST = 10.0.0.5
ENV PMA_PORT = 3306
ENV PMA_USER = operando
PMA_PASSWORD = winteriscomming

EXPOSE 80

CMD [ "phpmyadmin/phpmyadmin" ]
