# coding: utf-8

"""
    Policy DB

    The Policy Database that stores three types of documents in dedicated collections.   1) User Privacy Policy. Each OPERANDO user has one UPP document describing their privacy policies for each of the OSP services they are subscribed to. The UPP contains the current B2C privacy settings for a subscribed to OSP. The UPP contains the users privacy preferences. The UPP contains the G2C access policies for the OSP with justification for access.   2) The legislation policies. The regulations entered into OPERANDO using the OPERANDO regulation API.   3) The OSP descriptions and data requests. For each OSP its privacy policy, its access control rules, and the data it requests (as a workflow). For B2C, the set of privacy settings is stored. 

    OpenAPI spec version: 1.0.0
    Contact: support@operando.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.access_policy import AccessPolicy
from .models.access_reason import AccessReason
from .models.osp_consents import OSPConsents
from .models.osp_data_request import OSPDataRequest
from .models.osp_privacy_policy import OSPPrivacyPolicy
from .models.osp_privacy_policy_input import OSPPrivacyPolicyInput
from .models.osp_reason_policy import OSPReasonPolicy
from .models.osp_reason_policy_input import OSPReasonPolicyInput
from .models.osp_settings import OSPSettings
from .models.policy_attribute import PolicyAttribute
from .models.privacy_regulation import PrivacyRegulation
from .models.privacy_regulation_input import PrivacyRegulationInput
from .models.privacy_setting import PrivacySetting
from .models.user_preference import UserPreference
from .models.user_privacy_policy import UserPrivacyPolicy

# import apis into sdk package
from .apis.delete_api import DELETEApi
from .apis.get_api import GETApi
from .apis.legislation_api import LegislationApi
from .apis.osp_api import OSPApi
from .apis.post_api import POSTApi
from .apis.put_api import PUTApi
from .apis.upp_api import UPPApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
