# I take a official mono image https://hub.docker.com/_/mono/
# we choose normal 
FROM phpmyadmin/phpmyadmin

ENV MYSQL_ROOT_PASSWORD root
ENV PMA_HOST mysql.integration.operando.lan.esilab.org
ENV PMA_PORT 3306
ENV PMA_USER root
ENV PMA_PASSWORD root

EXPOSE 80

# CMD [ "phpmyadmin/phpmyadmin" ]
