swagger: '2.0'
info:
  title: eu.operando.core.logdb
  description: Operando LogDB module.
  version: "1.0.0"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost:8080
schemes:
- http
- https
produces:
- application/json
################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Log
    description: Inserts received data to the database by using Log4j.
  
################################################################################
#                                   Parameters                                 #
################################################################################

paths:
  /operando/core/logdb:
    post:
      summary: Inserts received data to the database.
      description: Inserts received data to the database by using Log4j.
      tags:
        - Log
      operationId: lodDB
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - name: request
        in: body
        description: The request data in JSON format to be inserted in the database by using Log4j
        schema:
          $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.logdb.yaml#/LogRequest'
        required: true
      responses:
        "200":
          description: Successful operation
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'