# coding: utf-8

"""
    eu.operando.interfaces.aapi

    Operandos AS interfaces

    OpenAPI spec version: 0.0.1
    Contact: kpatsak@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.attribute import Attribute
from .models.user import User
from .models.user_credential import UserCredential

# import apis into sdk package
from .apis.default_api import DefaultApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
