/*
 * eu.operando.core.ldb
 * Operando LogDB module.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * LogRequestTicket
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-21T08:54:23.905Z")
public class LogRequestTicket {
  @JsonProperty("userId")
  private String userId = null;

  /**
   * Source type from which comes the request.
   */
  public enum RequesterTypeEnum {
    @JsonProperty("PROCESS")
    PROCESS("PROCESS"),
    
    @JsonProperty("MODULE")
    MODULE("MODULE");

    private String value;

    RequesterTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("requesterType")
  private RequesterTypeEnum requesterType = null;

  @JsonProperty("requesterId")
  private String requesterId = null;

  /**
   * Priority level of the data to be logged.
   */
  public enum LogPriorityEnum {
    @JsonProperty("LOW")
    LOW("LOW"),
    
    @JsonProperty("NORMAL")
    NORMAL("NORMAL"),
    
    @JsonProperty("HIGH")
    HIGH("HIGH"),
    
    @JsonProperty("CRITICAL")
    CRITICAL("CRITICAL");

    private String value;

    LogPriorityEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("logPriority")
  private LogPriorityEnum logPriority = null;

  /**
   * Logging level.
   */
  public enum LogLevelEnum {
    @JsonProperty("INFO")
    INFO("INFO"),
    
    @JsonProperty("WARN")
    WARN("WARN"),
    
    @JsonProperty("ERROR")
    ERROR("ERROR"),
    
    @JsonProperty("FATAL")
    FATAL("FATAL");

    private String value;

    LogLevelEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("logLevel")
  private LogLevelEnum logLevel = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("keywords")
  private List<String> keywords = new ArrayList<String>();

  /**
   * Type of the data logged.
   */
  public enum LogTypeEnum {
    @JsonProperty("DATA_ACCESS")
    DATA_ACCESS("DATA_ACCESS"),
    
    @JsonProperty("SYSTEM")
    SYSTEM("SYSTEM"),
    
    @JsonProperty("NOTIFICATION")
    NOTIFICATION("NOTIFICATION"),
    
    @JsonProperty("OTHER")
    OTHER("OTHER");

    private String value;

    LogTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @JsonProperty("logType")
  private LogTypeEnum logType = null;

  @JsonProperty("affectedUserId")
  private String affectedUserId = null;

  public LogRequestTicket userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Id of the user.
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "Id of the user.")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public LogRequestTicket requesterType(RequesterTypeEnum requesterType) {
    this.requesterType = requesterType;
    return this;
  }

   /**
   * Source type from which comes the request.
   * @return requesterType
  **/
  @ApiModelProperty(example = "null", value = "Source type from which comes the request.")
  public RequesterTypeEnum getRequesterType() {
    return requesterType;
  }

  public void setRequesterType(RequesterTypeEnum requesterType) {
    this.requesterType = requesterType;
  }

  public LogRequestTicket requesterId(String requesterId) {
    this.requesterId = requesterId;
    return this;
  }

   /**
   * Id of the requester (e.g the id of an OSP).
   * @return requesterId
  **/
  @ApiModelProperty(example = "null", value = "Id of the requester (e.g the id of an OSP).")
  public String getRequesterId() {
    return requesterId;
  }

  public void setRequesterId(String requesterId) {
    this.requesterId = requesterId;
  }

  public LogRequestTicket logPriority(LogPriorityEnum logPriority) {
    this.logPriority = logPriority;
    return this;
  }

   /**
   * Priority level of the data to be logged.
   * @return logPriority
  **/
  @ApiModelProperty(example = "null", value = "Priority level of the data to be logged.")
  public LogPriorityEnum getLogPriority() {
    return logPriority;
  }

  public void setLogPriority(LogPriorityEnum logPriority) {
    this.logPriority = logPriority;
  }

  public LogRequestTicket logLevel(LogLevelEnum logLevel) {
    this.logLevel = logLevel;
    return this;
  }

   /**
   * Logging level.
   * @return logLevel
  **/
  @ApiModelProperty(example = "null", value = "Logging level.")
  public LogLevelEnum getLogLevel() {
    return logLevel;
  }

  public void setLogLevel(LogLevelEnum logLevel) {
    this.logLevel = logLevel;
  }

  public LogRequestTicket title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Subject of the event to be logged.
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "Subject of the event to be logged.")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public LogRequestTicket description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the event to be logged.
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "Description of the event to be logged.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public LogRequestTicket keywords(List<String> keywords) {
    this.keywords = keywords;
    return this;
  }

  public LogRequestTicket addKeywordsItem(String keywordsItem) {
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * Array of keywords to facilitate search
   * @return keywords
  **/
  @ApiModelProperty(example = "null", value = "Array of keywords to facilitate search")
  public List<String> getKeywords() {
    return keywords;
  }

  public void setKeywords(List<String> keywords) {
    this.keywords = keywords;
  }

  public LogRequestTicket logType(LogTypeEnum logType) {
    this.logType = logType;
    return this;
  }

   /**
   * Type of the data logged.
   * @return logType
  **/
  @ApiModelProperty(example = "null", value = "Type of the data logged.")
  public LogTypeEnum getLogType() {
    return logType;
  }

  public void setLogType(LogTypeEnum logType) {
    this.logType = logType;
  }

  public LogRequestTicket affectedUserId(String affectedUserId) {
    this.affectedUserId = affectedUserId;
    return this;
  }

   /**
   * Id of the affected user.
   * @return affectedUserId
  **/
  @ApiModelProperty(example = "null", value = "Id of the affected user.")
  public String getAffectedUserId() {
    return affectedUserId;
  }

  public void setAffectedUserId(String affectedUserId) {
    this.affectedUserId = affectedUserId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogRequestTicket logRequestTicket = (LogRequestTicket) o;
    return Objects.equals(this.userId, logRequestTicket.userId) &&
        Objects.equals(this.requesterType, logRequestTicket.requesterType) &&
        Objects.equals(this.requesterId, logRequestTicket.requesterId) &&
        Objects.equals(this.logPriority, logRequestTicket.logPriority) &&
        Objects.equals(this.logLevel, logRequestTicket.logLevel) &&
        Objects.equals(this.title, logRequestTicket.title) &&
        Objects.equals(this.description, logRequestTicket.description) &&
        Objects.equals(this.keywords, logRequestTicket.keywords) &&
        Objects.equals(this.logType, logRequestTicket.logType) &&
        Objects.equals(this.affectedUserId, logRequestTicket.affectedUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, requesterType, requesterId, logPriority, logLevel, title, description, keywords, logType, affectedUserId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogRequestTicket {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    requesterType: ").append(toIndentedString(requesterType)).append("\n");
    sb.append("    requesterId: ").append(toIndentedString(requesterId)).append("\n");
    sb.append("    logPriority: ").append(toIndentedString(logPriority)).append("\n");
    sb.append("    logLevel: ").append(toIndentedString(logLevel)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    logType: ").append(toIndentedString(logType)).append("\n");
    sb.append("    affectedUserId: ").append(toIndentedString(affectedUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

