/*
 * Policy DB
 * The Policy Database that stores three types of documents in dedicated collections.   1) User Privacy Policy. Each OPERANDO user has one UPP document describing their privacy policies for each of the OSP services they are subscribed to. The UPP contains the current B2C privacy settings for a subscribed to OSP. The UPP contains the users privacy preferences. The UPP contains the G2C access policies for the OSP with justification for access.   2) The legislation policies. The regulations entered into OPERANDO using the OPERANDO regulation API.   3) The OSP descriptions and data requests. For each OSP its privacy policy, its access control rules, and the data it requests (as a workflow). For B2C, the set of privacy settings is stored. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@operando.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.operando.core.pdb.client1.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PrivacySetting
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-13T14:33:54.425Z")
public class PrivacySetting {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("setting_key")
  private String settingKey = null;

  @SerializedName("setting_value")
  private String settingValue = null;

  public PrivacySetting id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * PrivacySetting Unique Identifier
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "PrivacySetting Unique Identifier")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PrivacySetting description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the setting
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "Description of the setting")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PrivacySetting name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Short name of the setting(e.g. visibility)
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Short name of the setting(e.g. visibility)")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PrivacySetting settingKey(String settingKey) {
    this.settingKey = settingKey;
    return this;
  }

   /**
   * Targeted setting key
   * @return settingKey
  **/
  @ApiModelProperty(example = "null", value = "Targeted setting key")
  public String getSettingKey() {
    return settingKey;
  }

  public void setSettingKey(String settingKey) {
    this.settingKey = settingKey;
  }

  public PrivacySetting settingValue(String settingValue) {
    this.settingValue = settingValue;
    return this;
  }

   /**
   * Targeted setting value
   * @return settingValue
  **/
  @ApiModelProperty(example = "null", value = "Targeted setting value")
  public String getSettingValue() {
    return settingValue;
  }

  public void setSettingValue(String settingValue) {
    this.settingValue = settingValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrivacySetting privacySetting = (PrivacySetting) o;
    return Objects.equals(this.id, privacySetting.id) &&
        Objects.equals(this.description, privacySetting.description) &&
        Objects.equals(this.name, privacySetting.name) &&
        Objects.equals(this.settingKey, privacySetting.settingKey) &&
        Objects.equals(this.settingValue, privacySetting.settingValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, description, name, settingKey, settingValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrivacySetting {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    settingKey: ").append(toIndentedString(settingKey)).append("\n");
    sb.append("    settingValue: ").append(toIndentedString(settingValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

