# coding: utf-8

"""
    Policy DB

    The Policy Database that stores three types of documents in dedicated collections.   1) User Privacy Policy. Each OPERANDO user has one UPP document describing their privacy policies for each of the OSP services they are subscribed to. The UPP contains the current B2C privacy settings for a subscribed to OSP. The UPP contains the users privacy preferences. The UPP contains the G2C access policies for the OSP with justification for access.   2) The legislation policies. The regulations entered into OPERANDO using the OPERANDO regulation API.   3) The OSP descriptions and data requests. For each OSP its privacy policy, its access control rules, and the data it requests (as a workflow). For B2C, the set of privacy settings is stored. 

    OpenAPI spec version: 1.0.0
    Contact: support@operando.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class LegislationApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def regulations_get(self, filter, **kwargs):
        """
        Perform a search query across the collection of regulation.
        The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_get(filter, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str filter: The query filter to be matched - ?filter={json description} (required)
        :return: list[PrivacyRegulation]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.regulations_get_with_http_info(filter, **kwargs)
        else:
            (data) = self.regulations_get_with_http_info(filter, **kwargs)
            return data

    def regulations_get_with_http_info(self, filter, **kwargs):
        """
        Perform a search query across the collection of regulation.
        The query contains a json object (names, values) and the request returns  the list of documents (regulations) where the filter matches i.e. the  document contains fields with those values. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_get_with_http_info(filter, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str filter: The query filter to be matched - ?filter={json description} (required)
        :return: list[PrivacyRegulation]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method regulations_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'filter' is set
        if ('filter' not in params) or (params['filter'] is None):
            raise ValueError("Missing the required parameter `filter` when calling `regulations_get`")


        collection_formats = {}

        resource_path = '/regulations/'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'filter' in params:
            query_params['filter'] = params['filter']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='list[PrivacyRegulation]',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def regulations_post(self, regulation, **kwargs):
        """
        Create a new legislation entry in the database.
        Called by the policy computation component when a new regulation is added to OPERANDO. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_post(regulation, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param PrivacyRegulationInput regulation: The first instance of this regulation document (required)
        :return: PrivacyRegulation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.regulations_post_with_http_info(regulation, **kwargs)
        else:
            (data) = self.regulations_post_with_http_info(regulation, **kwargs)
            return data

    def regulations_post_with_http_info(self, regulation, **kwargs):
        """
        Create a new legislation entry in the database.
        Called by the policy computation component when a new regulation is added to OPERANDO. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_post_with_http_info(regulation, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param PrivacyRegulationInput regulation: The first instance of this regulation document (required)
        :return: PrivacyRegulation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['regulation']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method regulations_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'regulation' is set
        if ('regulation' not in params) or (params['regulation'] is None):
            raise ValueError("Missing the required parameter `regulation` when calling `regulations_post`")


        collection_formats = {}

        resource_path = '/regulations/'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'regulation' in params:
            body_params = params['regulation']
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='PrivacyRegulation',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def regulations_reg_id_delete(self, reg_id, **kwargs):
        """
        Remove the PrivacyRegulation entry in the database.
        Called when by the policy computation component when the regulator api requests that the regulation be deleted. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_reg_id_delete(reg_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str reg_id: The identifier number of a regulation (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.regulations_reg_id_delete_with_http_info(reg_id, **kwargs)
        else:
            (data) = self.regulations_reg_id_delete_with_http_info(reg_id, **kwargs)
            return data

    def regulations_reg_id_delete_with_http_info(self, reg_id, **kwargs):
        """
        Remove the PrivacyRegulation entry in the database.
        Called when by the policy computation component when the regulator api requests that the regulation be deleted. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_reg_id_delete_with_http_info(reg_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str reg_id: The identifier number of a regulation (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['reg_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method regulations_reg_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'reg_id' is set
        if ('reg_id' not in params) or (params['reg_id'] is None):
            raise ValueError("Missing the required parameter `reg_id` when calling `regulations_reg_id_delete`")


        collection_formats = {}

        resource_path = '/regulations/{reg-id}/'.replace('{format}', 'json')
        path_params = {}
        if 'reg_id' in params:
            path_params['reg-id'] = params['reg_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def regulations_reg_id_get(self, reg_id, **kwargs):
        """
        Read a given legislation with its ID.
        Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_reg_id_get(reg_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str reg_id: The identifier number of a regulation (required)
        :return: PrivacyRegulation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.regulations_reg_id_get_with_http_info(reg_id, **kwargs)
        else:
            (data) = self.regulations_reg_id_get_with_http_info(reg_id, **kwargs)
            return data

    def regulations_reg_id_get_with_http_info(self, reg_id, **kwargs):
        """
        Read a given legislation with its ID.
        Get a specific legislation document via the id. This will return the  full legislation document in json format. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_reg_id_get_with_http_info(reg_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str reg_id: The identifier number of a regulation (required)
        :return: PrivacyRegulation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['reg_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method regulations_reg_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'reg_id' is set
        if ('reg_id' not in params) or (params['reg_id'] is None):
            raise ValueError("Missing the required parameter `reg_id` when calling `regulations_reg_id_get`")


        collection_formats = {}

        resource_path = '/regulations/{reg-id}/'.replace('{format}', 'json')
        path_params = {}
        if 'reg_id' in params:
            path_params['reg-id'] = params['reg_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='PrivacyRegulation',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def regulations_reg_id_put(self, reg_id, regulation, **kwargs):
        """
        Update PrivacyRegulation entry in the database.
        Called when by the policy computation component when the regulator api updates a regulation. Their new PrivacyRegulation document is stored in the policy DB. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_reg_id_put(reg_id, regulation, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str reg_id: The identifier number of a regulation (required)
        :param PrivacyRegulationInput regulation: The changed instance of this PrivacyRegulation (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.regulations_reg_id_put_with_http_info(reg_id, regulation, **kwargs)
        else:
            (data) = self.regulations_reg_id_put_with_http_info(reg_id, regulation, **kwargs)
            return data

    def regulations_reg_id_put_with_http_info(self, reg_id, regulation, **kwargs):
        """
        Update PrivacyRegulation entry in the database.
        Called when by the policy computation component when the regulator api updates a regulation. Their new PrivacyRegulation document is stored in the policy DB. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.regulations_reg_id_put_with_http_info(reg_id, regulation, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str reg_id: The identifier number of a regulation (required)
        :param PrivacyRegulationInput regulation: The changed instance of this PrivacyRegulation (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['reg_id', 'regulation']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method regulations_reg_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'reg_id' is set
        if ('reg_id' not in params) or (params['reg_id'] is None):
            raise ValueError("Missing the required parameter `reg_id` when calling `regulations_reg_id_put`")
        # verify the required parameter 'regulation' is set
        if ('regulation' not in params) or (params['regulation'] is None):
            raise ValueError("Missing the required parameter `regulation` when calling `regulations_reg_id_put`")


        collection_formats = {}

        resource_path = '/regulations/{reg-id}/'.replace('{format}', 'json')
        path_params = {}
        if 'reg_id' in params:
            path_params['reg-id'] = params['reg_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'regulation' in params:
            body_params = params['regulation']
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'PUT',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
