# coding: utf-8

"""
    Policy DB

    The Policy Database that stores three types of documents in dedicated collections.   1) User Privacy Policy. Each OPERANDO user has one UPP document describing their privacy policies for each of the OSP services they are subscribed to. The UPP contains the current B2C privacy settings for a subscribed to OSP. The UPP contains the users privacy preferences. The UPP contains the G2C access policies for the OSP with justification for access.   2) The legislation policies. The regulations entered into OPERANDO using the OPERANDO regulation API.   3) The OSP descriptions and data requests. For each OSP its privacy policy, its access control rules, and the data it requests (as a workflow). For B2C, the set of privacy settings is stored. 

    OpenAPI spec version: 1.0.0
    Contact: support@operando.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.upp_api import UPPApi


class TestUPPApi(unittest.TestCase):
    """ UPPApi unit test stubs """
    BASE_PATH = "http://10.136.24.87:8080"
    BASE_PATH = "http://integration.operando.esilab.org:8096/operando/core"

    def setUp(self):
        self.api = swagger_client.apis.upp_api.UPPApi()
        base_path = "".join([self.BASE_PATH, "/pdb"])
        api_client = swagger_client.ApiClient(host=base_path)
        self.api = swagger_client.apis.upp_api.UPPApi(api_client)

    def tearDown(self):
        pass

    # @unittest.skip("demo skipping")
    def test_upp_all(self):
        print("Test UPP all")
        print("Test case for user_privacy_policy_get with filter")
        upp_all_filter = "{\"user_id\":\"\"}"
        # upp_all_filter = "%7B%27user_id:%27%27%7D"
        api_response = self.api.user_privacy_policy_get(upp_all_filter)
        upp_list_length = len(api_response)
        self.assertNotEqual(api_response, None)
        try:
           assert len(api_response) > 0
        except Exception as e:
           print("Test UPP failed to get any stored upp")
           raise e
        upp = api_response[0]

        print("Test case for user_privacy_policy_post", upp_list_length)
        upp.user_id = "unittest_user"
        print("UPP for post:", upp)
        api_response = self.api.user_privacy_policy_post(upp)
        print("POST response:", api_response)
        self.assertNotEqual(api_response, None)
        upp_id = api_response

        print("Test case for user_privacy_policy_id_get")
        api_response = self.api.user_privacy_policy_user_id_get(upp_id)
        self.assertEqual(api_response.user_id, upp_id)

        print("Test case for user_privacy_policy_id_put")
        user_id = "unittest_user1"
        upp.user_id = user_id
        api_response = self.api.user_privacy_policy_user_id_put(upp_id, upp)
        print("PUT response", api_response)
        api_response = self.api.user_privacy_policy_user_id_get(user_id)
        self.assertEqual(api_response.user_id, user_id)

        print("Test case for user_privacy_policy_id_delete")
        api_response = self.api.user_privacy_policy_user_id_delete(user_id)
        print("DELETE:", api_response)

        api_response = self.api.user_privacy_policy_get(upp_all_filter)
        self.assertEqual(upp_list_length, len(api_response))


    def test_user_privacy_policy_get(self):
        """
        Test case for user_privacy_policy_get

        Perform a search query across the collection of UPPs.
        """
        pass

    def test_user_privacy_policy_post(self):
        """
        Test case for user_privacy_policy_post

        Create a new UPP entry in the database for the user.
        """
        pass

    def test_user_privacy_policy_user_id_delete(self):
        """
        Test case for user_privacy_policy_user_id_delete

        Remove the UPP entry in the database for the user.
        """
        pass

    def test_user_privacy_policy_user_id_get(self):
        """
        Test case for user_privacy_policy_user_id_get

        Read the user privacy policy for the given user id.
        """
        pass

    def test_user_privacy_policy_user_id_put(self):
        """
        Test case for user_privacy_policy_user_id_put

        Update UPP entry in the database for the user.
        """
        pass


if __name__ == '__main__':
    unittest.main()
