# coding: utf-8

"""
    eu.operando.interfaces.aapi

    Operandos AS interfaces

    OpenAPI spec version: 0.0.1
    Contact: kpatsak@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class User(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, username=None, password=None, required_attrs=None, optional_attrs=None, privacy_settings=None):
        """
        User - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.aapi_types = {
            'username': 'str',
            'password': 'str',
            'required_attrs': 'object',
            'optional_attrs': 'object',
            'privacy_settings': 'object'
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'required_attrs': 'required_attrs',
            'optional_attrs': 'optional_attrs',
            'privacy_settings': 'privacy_settings'
        }

        self._username = username
        self._password = password
        self._required_attrs = required_attrs
        self._optional_attrs = optional_attrs
        self._privacy_settings = privacy_settings

    @property
    def username(self):
        """
        Gets the username of this User.

        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this User.

        :param username: The username of this User.
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """
        Gets the password of this User.

        :return: The password of this User.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """
        Sets the password of this User.

        :param password: The password of this User.
        :type: str
        """

        self._password = password

    @property
    def required_attrs(self):
        """
        Gets the required_attrs of this User.

        :return: The required_attrs of this User.
        :rtype: object
        """
        return self._required_attrs

    @required_attrs.setter
    def required_attrs(self, required_attrs):
        """
        Sets the required_attrs of this User.

        :param required_attrs: The required_attrs of this User.
        :type: object
        """

        self._required_attrs = required_attrs

    @property
    def optional_attrs(self):
        """
        Gets the optional_attrs of this User.

        :return: The optional_attrs of this User.
        :rtype: object
        """
        return self._optional_attrs

    @optional_attrs.setter
    def optional_attrs(self, optional_attrs):
        """
        Sets the optional_attrs of this User.

        :param optional_attrs: The optional_attrs of this User.
        :type: object
        """

        self._optional_attrs = optional_attrs

    @property
    def privacy_settings(self):
        """
        Gets the privacy_settings of this User.

        :return: The privacy_settings of this User.
        :rtype: object
        """
        return self._privacy_settings

    @privacy_settings.setter
    def privacy_settings(self, privacy_settings):
        """
        Sets the privacy_settings of this User.

        :param privacy_settings: The privacy_settings of this User.
        :type: object
        """

        self._privacy_settings = privacy_settings

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.aapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, User):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
